#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v3
# autospec commit: c1050fe
#
Name     : R-brew
Version  : 1.0.10
Release  : 95
URL      : https://cran.r-project.org/src/contrib/brew_1.0-10.tar.gz
Source0  : https://cran.r-project.org/src/contrib/brew_1.0-10.tar.gz
Summary  : Templating Framework for Report Generation
Group    : Development/Tools
License  : GPL-2.0+
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
for report generation. brew template syntax is similar to PHP, Ruby's
    erb module, Java Server Pages, and Python's psp module.

%prep
%setup -q -n brew
pushd ..
cp -a brew buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1702944055

%install
export SOURCE_DATE_EPOCH=1702944055
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/brew/DESCRIPTION
/usr/lib64/R/library/brew/INDEX
/usr/lib64/R/library/brew/Meta/Rd.rds
/usr/lib64/R/library/brew/Meta/features.rds
/usr/lib64/R/library/brew/Meta/hsearch.rds
/usr/lib64/R/library/brew/Meta/links.rds
/usr/lib64/R/library/brew/Meta/nsInfo.rds
/usr/lib64/R/library/brew/Meta/package.rds
/usr/lib64/R/library/brew/NAMESPACE
/usr/lib64/R/library/brew/R/brew
/usr/lib64/R/library/brew/R/brew.rdb
/usr/lib64/R/library/brew/R/brew.rdx
/usr/lib64/R/library/brew/Sweave-test-1-006.pdf
/usr/lib64/R/library/brew/Sweave-test-1-007.pdf
/usr/lib64/R/library/brew/Sweave-test-1.tex
/usr/lib64/R/library/brew/brew-test-1-1.pdf
/usr/lib64/R/library/brew/brew-test-1.brew
/usr/lib64/R/library/brew/brew-test-1.tex
/usr/lib64/R/library/brew/brew-test-2-table.brew
/usr/lib64/R/library/brew/brew-test-2.brew
/usr/lib64/R/library/brew/brew-test-2.html
/usr/lib64/R/library/brew/brew-test-2.tex
/usr/lib64/R/library/brew/brew-test-3.brew
/usr/lib64/R/library/brew/broken.brew
/usr/lib64/R/library/brew/catprint.brew
/usr/lib64/R/library/brew/example1.brew
/usr/lib64/R/library/brew/example2.brew
/usr/lib64/R/library/brew/featurefull.brew
/usr/lib64/R/library/brew/help/AnIndex
/usr/lib64/R/library/brew/help/aliases.rds
/usr/lib64/R/library/brew/help/brew.rdb
/usr/lib64/R/library/brew/help/brew.rdx
/usr/lib64/R/library/brew/help/paths.rds
/usr/lib64/R/library/brew/html/00Index.html
/usr/lib64/R/library/brew/html/R.css
/usr/lib64/R/library/brew/tests/testthat.R
/usr/lib64/R/library/brew/tests/testthat/_snaps/catprintTest/brew.md
/usr/lib64/R/library/brew/tests/testthat/_snaps/extErr/error.md
/usr/lib64/R/library/brew/tests/testthat/_snaps/extraStackLayers/error.md
/usr/lib64/R/library/brew/tests/testthat/_snaps/file1/brew/brew-test-1-3.eps
/usr/lib64/R/library/brew/tests/testthat/_snaps/file1/brew/brew-test-1-4.eps
/usr/lib64/R/library/brew/tests/testthat/_snaps/file1/brew/test1.tex
/usr/lib64/R/library/brew/tests/testthat/_snaps/noextErr/error.md
/usr/lib64/R/library/brew/tests/testthat/_snaps/noextErrparm/error.md
/usr/lib64/R/library/brew/tests/testthat/_snaps/semFalseExt/error.md
/usr/lib64/R/library/brew/tests/testthat/_snaps/semFalseNoExt/error.md
/usr/lib64/R/library/brew/tests/testthat/_snaps/semTrueExt/error.md
/usr/lib64/R/library/brew/tests/testthat/_snaps/semTrueNoExt/error.md
/usr/lib64/R/library/brew/tests/testthat/brew-test-1.brew
/usr/lib64/R/library/brew/tests/testthat/brew-test-2.brew
/usr/lib64/R/library/brew/tests/testthat/catprint.brew
/usr/lib64/R/library/brew/tests/testthat/error.brew
/usr/lib64/R/library/brew/tests/testthat/test-brew.R
/usr/lib64/R/library/brew/tests/testthat/test-error.R
